//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerDatabaseModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerUserData
    {
        public int PlayerUDID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateJoined { get; set; }
    }
}
